http:
  routers:
    minio-api:
      rule: "Host(`minio.raspiska.local`)"
      service: "minio-api"
      entryPoints:
        - "web"
      middlewares:
        - "secure-headers"

    minio-console:
      rule: "Host(`minio-console.raspiska.local`)"
      service: "minio-console"
      entryPoints:
        - "web"
      middlewares:
        - "secure-headers"

  services:
    minio-api:
      loadBalancer:
        servers:
          - url: "http://raspiska_minio:9000"

    minio-console:
      loadBalancer:
        servers:
          - url: "http://raspiska_minio:9001"
