version: '3'

services:
  # Kong Database
  kong-database:
    image: postgres:13-alpine
    container_name: raspiska_kong_db
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: ${KONG_DB_PASSWORD:-kongpass}
    volumes:
      - kong_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - kong_network

  # Kong Migration
  kong-migration:
    image: kong/kong:3.3.1
    container_name: raspiska_kong_migration
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: ${KONG_DB_PASSWORD:-kongpass}
      KONG_PG_DATABASE: kong
    command: kong migrations bootstrap
    restart: on-failure
    networks:
      - kong_network

  # Kong API Gateway
  kong:
    image: kong/kong:3.3.1
    container_name: raspiska_kong
    depends_on:
      kong-database:
        condition: service_healthy
      kong-migration:
        condition: service_completed_successfully
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: ${KONG_DB_PASSWORD:-kongpass}
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_STATUS_LISTEN: 0.0.0.0:8100
    ports:
      - "8000:8000" # Kong Proxy
      - "8443:8443" # Kong Proxy SSL
      - "8001:8001" # Kong Admin API
      - "8444:8444" # Kong Admin API SSL
      - "8100:8100" # Kong Status API
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - kong_network
      - traefik_network
      - redis_network
      - valkey_network

  # Note: Konga has been removed due to ARM64 compatibility issues
  # You can use Kong's Admin API directly at http://localhost:8001

volumes:
  kong_data:
    name: raspiska_kong_data

networks:
  kong_network:
    name: raspiska_kong_network
  traefik_network:
    external: true
    name: raspiska_traefik_network
  redis_network:
    external: true
    name: raspiska_redis_network
  valkey_network:
    external: true
    name: raspiska_valkey_network
