global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Self monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['raspiska_traefik:8080']
    metrics_path: /metrics

  # Node Exporter metrics (host system)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Valkey metrics
  - job_name: 'valkey'
    static_configs:
      - targets: ['valkey-exporter:9121']

  # PostgreSQL metrics (for Kong, Keycloak, and n8n)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Kong API Gateway metrics
  - job_name: 'kong'
    scrape_interval: 10s
    metrics_path: /probe
    params:
      module: [http_2xx]
      target: ['raspiska_kong:8001']
    static_configs:
      - targets: ['kong-exporter:9115']
        labels:
          instance: 'kong'
          service: 'kong'

  # Keycloak metrics
  - job_name: 'keycloak'
    static_configs:
      - targets: ['raspiska_keycloak:8080']
    metrics_path: /auth/metrics
    
  # n8n metrics
  - job_name: 'n8n'
    static_configs:
      - targets: ['raspiska_n8n:5678']
    metrics_path: /metrics
